<?php

/**
 * @file
 * Contains event_ticket.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function event_ticket_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_ticket module.
    case 'help.page.event_ticket':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Event Ticketing with Drupal Commerce') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function event_ticket_theme() {
  $theme = [];
  $theme['event_ticket'] = [
    'render element' => 'elements',
    'file' => 'event_ticket.page.inc',
    'template' => 'event_ticket',
  ];
  $theme['event_ticket_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'event_ticket.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_entity_type_alter().
 */
function event_ticket_entity_type_alter(array &$entity_types) {
  $entity_types['event']->setLinkTemplate('event-ticket-overview', '/event/{event}/tickets');
  $entity_types['event']->setLinkTemplate('event-ticket-list', '/event/{event}/tickets/list');
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function event_ticket_theme_suggestions_event_ticket(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#event_ticket'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'event_ticket__' . $sanitized_view_mode;
  $suggestions[] = 'event_ticket__' . $entity->bundle();
  $suggestions[] = 'event_ticket__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'event_ticket__' . $entity->id();
  $suggestions[] = 'event_ticket__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
